# Generated by Django 5.0.6 on 2024-06-09 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="media")),
                ("description", models.TextField()),
                ("rank", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="media")),
                ("rank", models.IntegerField()),
                ("slug", models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo", models.CharField(blank=True, max_length=200)),
                ("slug", models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("post", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="media")),
                ("comment", models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("firstname", models.CharField(max_length=500)),
                ("lastname", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=500)),
                ("phone_number", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fonepay", "Fonepay"),
                            ("Cash On Delivery", "Cash On Delivery"),
                        ],
                        default=False,
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=500, unique=True)),
                ("star", models.IntegerField()),
                ("comment", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="media")),
                ("description", models.TextField(blank=True)),
                ("rank", models.IntegerField()),
                ("url", models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("discounted_price", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="media")),
                ("description", models.TextField(blank=True)),
                ("specification", models.TextField(blank=True)),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("in_stock", "In_Stock"),
                            ("out of stock", "Out of Stock"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "labels",
                    models.CharField(
                        choices=[
                            ("", "default"),
                            ("new", "new"),
                            ("sale", "sale"),
                            ("hot", "hot"),
                        ],
                        max_length=50,
                    ),
                ),
                ("slug", models.CharField(max_length=500, unique=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=500)),
                ("quantity", models.FloatField()),
                ("total", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("checkout", models.BooleanField(default=False)),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=500)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("checkout", models.BooleanField(default=False)),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
            ],
        ),
    ]
