# Generated by Django 5.0.6 on 2024-07-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_brand_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Fonepay", "Fonepay"),
                    ("Cash On Delivery", "Cash On Delivery"),
                ],
                max_length=20,
            ),
        ),
    ]
