# Generated by Django 5.0.6 on 2024-07-09 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_orderdetail_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="media")),
                ("quantity", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=500)),
                ("total", models.CharField(max_length=500)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.orderdetail",
                    ),
                ),
            ],
        ),
    ]
