# Generated by Django 5.0.6 on 2024-07-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_orderdetail_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="grandtotal",
            field=models.FloatField(default=0),
        ),
    ]
