# Generated by Django 5.0.6 on 2024-07-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_cart_grandtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="grandtotal",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
