# Generated by Django 5.0.6 on 2024-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_cart_grandtotal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="grandtotal",
        ),
        migrations.AddField(
            model_name="cart",
            name="image",
            field=models.ImageField(default=0, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="total",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
