# Generated by Django 5.0.6 on 2024-07-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_remove_cart_grandtotal_cart_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="image",
            field=models.ImageField(default=None, upload_to="media"),
        ),
    ]
