# Generated by Django 5.0.6 on 2024-07-12 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_cart_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="image",
        ),
    ]
