# Generated by Django 5.0.6 on 2024-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.CharField(max_length=1000),
        ),
    ]
