# Generated by Django 5.0.6 on 2024-07-12 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
    ]
