# Generated by Django 5.0.6 on 2024-07-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.CharField(max_length=5000),
        ),
    ]
