# Generated by Django 5.0.6 on 2024-07-13 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_alter_orderdetail_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="user",
        ),
    ]
