# Generated by Django 5.0.6 on 2024-07-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_remove_orderdetail_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="grandtotal",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
