# Generated by Django 5.0.6 on 2024-07-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_cart_grandtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="slug",
            field=models.CharField(max_length=500),
        ),
    ]
