# Generated by Django 5.0.6 on 2024-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_alter_productreview_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
